apiVersion: apps/v1
kind: Deployment
metadata:
  name: prova
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prova
  template:
    metadata:
      labels:
        app: prova
    spec:
      containers:
      - name: prova
        image: marianichelle/prova
        ports:
        - containerPort: 8000
