apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: marianichelle/prova
  newTag: 77396bd1d92eb76e5b0bc1ca03568c03a0f1444a
- name: prova
  newName: marianichelle/prova
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
