name: ci
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 
          password: ${{ secrets.DOCKERHUB_TOKEN }} # 

      - name: Build and Push to DockerHub
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true # 
          tags: your-dockerhub-username/ci-sum-python:${{ github.sha }} #